import type { AthleteCard, PlayCard } from './types'

/**
 * The master pools. Athlete archetypes are dealt into per-game rosters (see
 * engine.buildRoster); play cards form the coach's draw pile. Stats are tuned
 * for a rotation rhythm of roughly a quarter on court before needing rest.
 */

export const ATHLETES: AthleteCard[] = [
  // --- Point Guards ---
  {
    id: 'floor-general',
    name: 'Floor General',
    kind: 'athlete',
    position: 'PG',
    off: 3,
    def: 2,
    sta: 5,
    ability: 'playmaker',
    abilityText: 'Playmaker: +1 coach energy each possession while on court.',
  },
  {
    id: 'speedster',
    name: 'Speedster',
    kind: 'athlete',
    position: 'PG',
    off: 4,
    def: 1,
    sta: 5,
    ability: 'fastBreak',
    abilityText: 'Fast Break: +2 OFF vs a tired (2 STA or less) or missing defender.',
  },
  {
    id: 'veteran-pg',
    name: 'Veteran PG',
    kind: 'athlete',
    position: 'PG',
    off: 3,
    def: 3,
    sta: 6,
    ability: 'iron',
    abilityText: 'Iron: the first time he would gas out, holds at 1 STA.',
  },

  // --- Shooting Guards ---
  {
    id: 'sharpshooter',
    name: 'Sharpshooter',
    kind: 'athlete',
    position: 'SG',
    off: 5,
    def: 1,
    sta: 4,
    ability: 'clutch',
    abilityText: 'Clutch: +2 OFF in the 4th quarter and overtime.',
  },
  {
    id: 'three-and-d',
    name: '3&D Wing',
    kind: 'athlete',
    position: 'SG',
    off: 3,
    def: 4,
    sta: 5,
  },
  {
    id: 'rookie-sg',
    name: 'Rookie SG',
    kind: 'athlete',
    position: 'SG',
    off: 3,
    def: 2,
    sta: 8,
    abilityText: 'High motor: modest ratings, but he never seems to tire.',
  },

  // --- Small Forwards ---
  {
    id: 'athletic-wing',
    name: 'Athletic Wing',
    kind: 'athlete',
    position: 'SF',
    off: 4,
    def: 3,
    sta: 6,
    ability: 'hustle',
    abilityText: 'Hustle: +1 OFF per possession on court (max +3). Resets when subbed.',
  },
  {
    id: 'slasher',
    name: 'Slasher',
    kind: 'athlete',
    position: 'SF',
    off: 4,
    def: 2,
    sta: 5,
    ability: 'fastBreak',
    abilityText: 'Fast Break: +2 OFF vs a tired (2 STA or less) or missing defender.',
  },
  {
    id: 'two-way-forward',
    name: 'Two-Way Forward',
    kind: 'athlete',
    position: 'SF',
    off: 4,
    def: 4,
    sta: 6,
  },

  // --- Power Forwards ---
  {
    id: 'stretch-four',
    name: 'Stretch Four',
    kind: 'athlete',
    position: 'PF',
    off: 5,
    def: 2,
    sta: 5,
  },
  {
    id: 'lockdown-pf',
    name: 'Lockdown PF',
    kind: 'athlete',
    position: 'PF',
    off: 1,
    def: 5,
    sta: 6,
    ability: 'anchor',
    abilityText: 'Anchor: a defensive wall.',
  },
  {
    id: 'bruiser',
    name: 'Bruiser',
    kind: 'athlete',
    position: 'PF',
    off: 4,
    def: 4,
    sta: 7,
    ability: 'rebound',
    abilityText: 'Rebound: recovers 1 STA each possession on court.',
  },

  // --- Centers ---
  {
    id: 'big-man',
    name: 'Big Man',
    kind: 'athlete',
    position: 'C',
    off: 5,
    def: 4,
    sta: 8,
    ability: 'rebound',
    abilityText: 'Rebound: recovers 1 STA each possession on court.',
  },
  {
    id: 'rim-protector',
    name: 'Rim Protector',
    kind: 'athlete',
    position: 'C',
    off: 2,
    def: 6,
    sta: 6,
    ability: 'wall',
    abilityText: 'Wall: locks down the paint.',
  },
  {
    id: 'franchise-center',
    name: 'Franchise Center',
    kind: 'athlete',
    position: 'C',
    off: 7,
    def: 5,
    sta: 7,
    ability: 'takeover',
    abilityText: 'Takeover: +1 OFF to your other athletes on court.',
  },
]

export const PLAYS: PlayCard[] = [
  {
    id: 'clutch-gene',
    name: 'Clutch Gene',
    kind: 'play',
    cost: 1,
    effect: 'clutchGene',
    target: 'ally',
    text: '+3 OFF to a target athlete this clash.',
  },
  {
    id: 'fast-break',
    name: 'Fast Break',
    kind: 'play',
    cost: 0,
    effect: 'fastBreakEnergy',
    target: 'self',
    text: '+2 coach energy this possession.',
  },
  {
    id: 'timeout',
    name: 'Timeout',
    kind: 'play',
    cost: 1,
    effect: 'timeout',
    target: 'ally',
    text: 'Restore 3 STA to a target athlete.',
  },
  {
    id: 'flop',
    name: 'Flop',
    kind: 'play',
    cost: 2,
    effect: 'flop',
    target: 'enemy',
    text: 'Draw a foul on a target enemy athlete.',
  },
  {
    id: 'zone-defense',
    name: 'Zone Defense',
    kind: 'play',
    cost: 2,
    effect: 'zoneDefense',
    target: 'none',
    text: 'All your athletes +2 DEF this clash.',
  },
  {
    id: 'full-court-press',
    name: 'Full Court Press',
    kind: 'play',
    cost: 2,
    effect: 'fullCourtPress',
    target: 'none',
    text: 'Enemy athletes on court get -2 OFF this clash.',
  },
]
