import type { AthleteCard, Card, PowerUpCard } from './types'

/**
 * The master card pool. `id` is the template id; deployed instances and deck
 * copies get their own unique ids (see buildDeck / engine). Stats are tuned
 * for a snappy ~4-quarter match and can be rebalanced freely here.
 */

export const ATHLETES: AthleteCard[] = [
  // --- Point Guards ---
  {
    id: 'floor-general',
    name: 'Floor General',
    kind: 'athlete',
    position: 'PG',
    cost: 2,
    off: 3,
    def: 2,
    sta: 3,
    ability: 'playmaker',
    abilityText: 'Playmaker: +1 energy next turn while on court.',
  },
  {
    id: 'speedster',
    name: 'Speedster',
    kind: 'athlete',
    position: 'PG',
    cost: 2,
    off: 4,
    def: 1,
    sta: 3,
    ability: 'fastBreak',
    abilityText: 'Fast Break: +2 OFF when the opposing slot is empty.',
  },
  {
    id: 'veteran-pg',
    name: 'Veteran PG',
    kind: 'athlete',
    position: 'PG',
    cost: 3,
    off: 3,
    def: 3,
    sta: 4,
    ability: 'iron',
    abilityText: 'Iron: survives its first foul-out at 1 stamina.',
  },

  // --- Shooting Guards ---
  {
    id: 'sharpshooter',
    name: 'Sharpshooter',
    kind: 'athlete',
    position: 'SG',
    cost: 3,
    off: 5,
    def: 1,
    sta: 2,
    ability: 'clutch',
    abilityText: 'Clutch: +2 OFF in the 4th quarter and overtime.',
  },
  {
    id: 'three-and-d',
    name: '3&D Wing',
    kind: 'athlete',
    position: 'SG',
    cost: 3,
    off: 3,
    def: 4,
    sta: 3,
  },
  {
    id: 'rookie-sg',
    name: 'Rookie SG',
    kind: 'athlete',
    position: 'SG',
    cost: 1,
    off: 2,
    def: 1,
    sta: 3,
  },

  // --- Small Forwards ---
  {
    id: 'athletic-wing',
    name: 'Athletic Wing',
    kind: 'athlete',
    position: 'SF',
    cost: 3,
    off: 4,
    def: 3,
    sta: 4,
    ability: 'hustle',
    abilityText: 'Hustle: +1 OFF for each turn survived.',
  },
  {
    id: 'slasher',
    name: 'Slasher',
    kind: 'athlete',
    position: 'SF',
    cost: 2,
    off: 4,
    def: 2,
    sta: 3,
    ability: 'fastBreak',
    abilityText: 'Fast Break: +2 OFF when the opposing slot is empty.',
  },
  {
    id: 'two-way-forward',
    name: 'Two-Way Forward',
    kind: 'athlete',
    position: 'SF',
    cost: 4,
    off: 4,
    def: 4,
    sta: 4,
  },

  // --- Power Forwards ---
  {
    id: 'stretch-four',
    name: 'Stretch Four',
    kind: 'athlete',
    position: 'PF',
    cost: 3,
    off: 5,
    def: 2,
    sta: 3,
  },
  {
    id: 'lockdown-pf',
    name: 'Lockdown PF',
    kind: 'athlete',
    position: 'PF',
    cost: 2,
    off: 1,
    def: 5,
    sta: 4,
    ability: 'anchor',
    abilityText: 'Anchor: a defensive wall.',
  },
  {
    id: 'bruiser',
    name: 'Bruiser',
    kind: 'athlete',
    position: 'PF',
    cost: 4,
    off: 4,
    def: 4,
    sta: 5,
    ability: 'rebound',
    abilityText: 'Rebound: +1 stamina each turn.',
  },

  // --- Centers ---
  {
    id: 'big-man',
    name: 'Big Man',
    kind: 'athlete',
    position: 'C',
    cost: 4,
    off: 5,
    def: 4,
    sta: 6,
    ability: 'rebound',
    abilityText: 'Rebound: +1 stamina each turn.',
  },
  {
    id: 'rim-protector',
    name: 'Rim Protector',
    kind: 'athlete',
    position: 'C',
    cost: 3,
    off: 2,
    def: 6,
    sta: 4,
    ability: 'wall',
    abilityText: 'Wall: locks down the paint.',
  },
  {
    id: 'franchise-center',
    name: 'Franchise Center',
    kind: 'athlete',
    position: 'C',
    cost: 6,
    off: 7,
    def: 5,
    sta: 6,
    ability: 'takeover',
    abilityText: 'Takeover: +1 OFF to your other athletes.',
  },
]

export const POWER_UPS: PowerUpCard[] = [
  {
    id: 'clutch-gene',
    name: 'Clutch Gene',
    kind: 'powerup',
    cost: 1,
    effect: 'clutchGene',
    target: 'ally',
    text: '+3 OFF to a target ally this clash.',
  },
  {
    id: 'fast-break',
    name: 'Fast Break',
    kind: 'powerup',
    cost: 1,
    effect: 'fastBreakEnergy',
    target: 'self',
    text: '+2 energy this turn.',
  },
  {
    id: 'timeout',
    name: 'Timeout',
    kind: 'powerup',
    cost: 1,
    effect: 'timeout',
    target: 'ally',
    text: 'Restore a target ally to full stamina.',
  },
  {
    id: 'tech-foul',
    name: 'Tech Foul',
    kind: 'powerup',
    cost: 2,
    effect: 'techFoul',
    target: 'enemy',
    text: 'Deal 4 damage to a target enemy athlete.',
  },
  {
    id: 'zone-defense',
    name: 'Zone Defense',
    kind: 'powerup',
    cost: 2,
    effect: 'zoneDefense',
    target: 'none',
    text: 'All your athletes +2 DEF this clash.',
  },
  {
    id: 'full-court-press',
    name: 'Full Court Press',
    kind: 'powerup',
    cost: 2,
    effect: 'fullCourtPress',
    target: 'none',
    text: 'All enemy athletes -2 OFF this clash.',
  },
]

export const CARD_POOL: Card[] = [...ATHLETES, ...POWER_UPS]
